// Generated from NPB.jp 2025 team batting, pitching, and fielding stat pages.
// Keep this static so the GitHub Pages build can run fully in the browser.
export interface NpbGeneratedHitter {
  name: string;
  team: string;
  sourceUrl: string;
  position: string;
  positionDetail?: string;
  games: number;
  pa: number;
  ab: number;
  runs: number;
  hits: number;
  doubles: number;
  triples: number;
  homeRuns: number;
  rbi: number;
  steals: number;
  walks: number;
  strikeouts: number;
  avg: number;
  slg: number;
  obp: number;
  fieldingSeed: number;
}

export interface NpbGeneratedPitcher {
  name: string;
  team: string;
  sourceUrl: string;
  pitchingRole: "先発" | "中継ぎ" | "抑え";
  games: number;
  wins: number;
  losses: number;
  battersFaced: number;
  innings: number;
  hitsAllowed: number;
  homeRunsAllowed: number;
  walks: number;
  strikeouts: number;
  runsAllowed: number;
  earnedRuns: number;
  eraValue: number;
}

export const EXTRA_RAW_HITTERS: NpbGeneratedHitter[] = [
  {
    "team": "読売ジャイアンツ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_g.html",
    "name": "泉口 友汰",
    "position": "遊撃手",
    "games": 133,
    "pa": 573,
    "ab": 512,
    "runs": 67,
    "hits": 154,
    "doubles": 23,
    "triples": 3,
    "homeRuns": 6,
    "rbi": 39,
    "steals": 4,
    "walks": 47,
    "strikeouts": 60,
    "avg": 0.301,
    "slg": 0.393,
    "obp": 0.362,
    "positionDetail": "内野手",
    "fieldingSeed": 14
  },
  {
    "team": "読売ジャイアンツ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_g.html",
    "name": "キャベッジ",
    "position": "外野手",
    "games": 123,
    "pa": 476,
    "ab": 431,
    "runs": 50,
    "hits": 115,
    "doubles": 26,
    "triples": 1,
    "homeRuns": 17,
    "rbi": 51,
    "steals": 5,
    "walks": 37,
    "strikeouts": 144,
    "avg": 0.267,
    "slg": 0.45,
    "obp": 0.331,
    "positionDetail": "外野手",
    "fieldingSeed": 8
  },
  {
    "team": "読売ジャイアンツ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_g.html",
    "name": "吉川 尚輝",
    "position": "二塁手",
    "games": 107,
    "pa": 455,
    "ab": 404,
    "runs": 33,
    "hits": 112,
    "doubles": 15,
    "triples": 3,
    "homeRuns": 3,
    "rbi": 32,
    "steals": 8,
    "walks": 41,
    "strikeouts": 63,
    "avg": 0.277,
    "slg": 0.351,
    "obp": 0.349,
    "positionDetail": "内野手",
    "fieldingSeed": 14
  },
  {
    "team": "読売ジャイアンツ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_g.html",
    "name": "丸 佳浩",
    "position": "外野手",
    "games": 90,
    "pa": 369,
    "ab": 326,
    "runs": 30,
    "hits": 87,
    "doubles": 19,
    "triples": 3,
    "homeRuns": 6,
    "rbi": 26,
    "steals": 5,
    "walks": 40,
    "strikeouts": 57,
    "avg": 0.267,
    "slg": 0.399,
    "obp": 0.345,
    "positionDetail": "外野手",
    "fieldingSeed": 7
  },
  {
    "team": "読売ジャイアンツ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_g.html",
    "name": "中山 礼都",
    "position": "外野手",
    "games": 103,
    "pa": 312,
    "ab": 287,
    "runs": 35,
    "hits": 76,
    "doubles": 13,
    "triples": 0,
    "homeRuns": 7,
    "rbi": 32,
    "steals": 1,
    "walks": 20,
    "strikeouts": 42,
    "avg": 0.265,
    "slg": 0.383,
    "obp": 0.319,
    "positionDetail": "外野手",
    "fieldingSeed": 8
  },
  {
    "team": "読売ジャイアンツ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_g.html",
    "name": "岸田 行倫",
    "position": "捕手",
    "games": 87,
    "pa": 299,
    "ab": 266,
    "runs": 25,
    "hits": 78,
    "doubles": 9,
    "triples": 0,
    "homeRuns": 8,
    "rbi": 39,
    "steals": 0,
    "walks": 25,
    "strikeouts": 44,
    "avg": 0.293,
    "slg": 0.417,
    "obp": 0.355,
    "fieldingSeed": 16
  },
  {
    "team": "読売ジャイアンツ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_g.html",
    "name": "岡本 和真",
    "position": "三塁手",
    "games": 69,
    "pa": 293,
    "ab": 251,
    "runs": 38,
    "hits": 82,
    "doubles": 21,
    "triples": 1,
    "homeRuns": 15,
    "rbi": 49,
    "steals": 1,
    "walks": 33,
    "strikeouts": 33,
    "avg": 0.327,
    "slg": 0.598,
    "obp": 0.416,
    "positionDetail": "内野手",
    "fieldingSeed": 7
  },
  {
    "team": "読売ジャイアンツ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_g.html",
    "name": "増田 陸",
    "position": "一塁手",
    "games": 87,
    "pa": 286,
    "ab": 264,
    "runs": 22,
    "hits": 61,
    "doubles": 10,
    "triples": 0,
    "homeRuns": 5,
    "rbi": 21,
    "steals": 0,
    "walks": 13,
    "strikeouts": 62,
    "avg": 0.231,
    "slg": 0.326,
    "obp": 0.272,
    "positionDetail": "内野手",
    "fieldingSeed": 5
  },
  {
    "team": "読売ジャイアンツ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_g.html",
    "name": "リチャード",
    "position": "一塁手",
    "games": 77,
    "pa": 253,
    "ab": 232,
    "runs": 17,
    "hits": 49,
    "doubles": 7,
    "triples": 0,
    "homeRuns": 11,
    "rbi": 39,
    "steals": 1,
    "walks": 13,
    "strikeouts": 90,
    "avg": 0.211,
    "slg": 0.384,
    "obp": 0.269,
    "positionDetail": "内野手",
    "fieldingSeed": 6
  },
  {
    "team": "中日ドラゴンズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_d.html",
    "name": "岡林 勇希",
    "position": "外野手",
    "games": 143,
    "pa": 637,
    "ab": 578,
    "runs": 71,
    "hits": 168,
    "doubles": 22,
    "triples": 8,
    "homeRuns": 5,
    "rbi": 35,
    "steals": 17,
    "walks": 51,
    "strikeouts": 57,
    "avg": 0.291,
    "slg": 0.382,
    "obp": 0.348,
    "positionDetail": "外野手",
    "fieldingSeed": 7
  },
  {
    "team": "中日ドラゴンズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_d.html",
    "name": "上林 誠知",
    "position": "外野手",
    "games": 134,
    "pa": 517,
    "ab": 486,
    "runs": 52,
    "hits": 131,
    "doubles": 21,
    "triples": 4,
    "homeRuns": 17,
    "rbi": 52,
    "steals": 27,
    "walks": 20,
    "strikeouts": 102,
    "avg": 0.27,
    "slg": 0.434,
    "obp": 0.303,
    "positionDetail": "外野手",
    "fieldingSeed": 8
  },
  {
    "team": "中日ドラゴンズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_d.html",
    "name": "ボスラー",
    "position": "一塁手",
    "games": 122,
    "pa": 493,
    "ab": 452,
    "runs": 37,
    "hits": 118,
    "doubles": 33,
    "triples": 2,
    "homeRuns": 13,
    "rbi": 58,
    "steals": 0,
    "walks": 30,
    "strikeouts": 101,
    "avg": 0.261,
    "slg": 0.429,
    "obp": 0.312,
    "positionDetail": "内野手",
    "fieldingSeed": 6
  },
  {
    "team": "中日ドラゴンズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_d.html",
    "name": "細川 成也",
    "position": "外野手",
    "games": 108,
    "pa": 428,
    "ab": 360,
    "runs": 38,
    "hits": 92,
    "doubles": 22,
    "triples": 1,
    "homeRuns": 20,
    "rbi": 58,
    "steals": 2,
    "walks": 61,
    "strikeouts": 109,
    "avg": 0.256,
    "slg": 0.489,
    "obp": 0.367,
    "positionDetail": "外野手",
    "fieldingSeed": 7
  },
  {
    "team": "中日ドラゴンズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_d.html",
    "name": "山本 泰寛",
    "position": "遊撃手",
    "games": 112,
    "pa": 372,
    "ab": 347,
    "runs": 23,
    "hits": 84,
    "doubles": 12,
    "triples": 2,
    "homeRuns": 4,
    "rbi": 23,
    "steals": 3,
    "walks": 10,
    "strikeouts": 62,
    "avg": 0.242,
    "slg": 0.323,
    "obp": 0.265,
    "positionDetail": "内野手",
    "fieldingSeed": 15
  },
  {
    "team": "中日ドラゴンズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_d.html",
    "name": "田中 幹也",
    "position": "二塁手",
    "games": 95,
    "pa": 365,
    "ab": 315,
    "runs": 33,
    "hits": 85,
    "doubles": 13,
    "triples": 1,
    "homeRuns": 1,
    "rbi": 21,
    "steals": 12,
    "walks": 24,
    "strikeouts": 35,
    "avg": 0.27,
    "slg": 0.327,
    "obp": 0.324,
    "positionDetail": "内野手",
    "fieldingSeed": 14
  },
  {
    "team": "中日ドラゴンズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_d.html",
    "name": "石伊 雄太",
    "position": "捕手",
    "games": 85,
    "pa": 270,
    "ab": 235,
    "runs": 17,
    "hits": 52,
    "doubles": 9,
    "triples": 0,
    "homeRuns": 3,
    "rbi": 21,
    "steals": 0,
    "walks": 14,
    "strikeouts": 63,
    "avg": 0.221,
    "slg": 0.298,
    "obp": 0.272,
    "fieldingSeed": 14
  },
  {
    "team": "中日ドラゴンズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_d.html",
    "name": "板山 祐太郎",
    "position": "二塁手",
    "games": 84,
    "pa": 193,
    "ab": 179,
    "runs": 17,
    "hits": 37,
    "doubles": 5,
    "triples": 2,
    "homeRuns": 2,
    "rbi": 10,
    "steals": 0,
    "walks": 10,
    "strikeouts": 50,
    "avg": 0.207,
    "slg": 0.291,
    "obp": 0.251,
    "positionDetail": "内野手",
    "fieldingSeed": 13
  },
  {
    "team": "中日ドラゴンズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_d.html",
    "name": "カリステ",
    "position": "一塁手",
    "games": 61,
    "pa": 192,
    "ab": 176,
    "runs": 13,
    "hits": 40,
    "doubles": 9,
    "triples": 1,
    "homeRuns": 1,
    "rbi": 14,
    "steals": 1,
    "walks": 12,
    "strikeouts": 37,
    "avg": 0.227,
    "slg": 0.307,
    "obp": 0.272,
    "positionDetail": "内野手",
    "fieldingSeed": 6
  },
  {
    "team": "広島東洋カープ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_c.html",
    "name": "小園 海斗",
    "position": "三塁手",
    "games": 138,
    "pa": 573,
    "ab": 521,
    "runs": 51,
    "hits": 161,
    "doubles": 24,
    "triples": 4,
    "homeRuns": 3,
    "rbi": 47,
    "steals": 12,
    "walks": 42,
    "strikeouts": 47,
    "avg": 0.309,
    "slg": 0.388,
    "obp": 0.365,
    "positionDetail": "内野手",
    "fieldingSeed": 7
  },
  {
    "team": "広島東洋カープ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_c.html",
    "name": "ファビアン",
    "position": "外野手",
    "games": 138,
    "pa": 572,
    "ab": 539,
    "runs": 60,
    "hits": 149,
    "doubles": 30,
    "triples": 0,
    "homeRuns": 17,
    "rbi": 65,
    "steals": 2,
    "walks": 22,
    "strikeouts": 84,
    "avg": 0.276,
    "slg": 0.427,
    "obp": 0.315,
    "positionDetail": "外野手",
    "fieldingSeed": 8
  },
  {
    "team": "広島東洋カープ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_c.html",
    "name": "末包 昇大",
    "position": "外野手",
    "games": 123,
    "pa": 477,
    "ab": 437,
    "runs": 40,
    "hits": 106,
    "doubles": 18,
    "triples": 3,
    "homeRuns": 11,
    "rbi": 62,
    "steals": 2,
    "walks": 33,
    "strikeouts": 97,
    "avg": 0.243,
    "slg": 0.373,
    "obp": 0.296,
    "positionDetail": "外野手",
    "fieldingSeed": 9
  },
  {
    "team": "広島東洋カープ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_c.html",
    "name": "坂倉 将吾",
    "position": "捕手",
    "games": 104,
    "pa": 399,
    "ab": 345,
    "runs": 29,
    "hits": 82,
    "doubles": 26,
    "triples": 1,
    "homeRuns": 5,
    "rbi": 37,
    "steals": 1,
    "walks": 43,
    "strikeouts": 72,
    "avg": 0.238,
    "slg": 0.362,
    "obp": 0.327,
    "fieldingSeed": 14
  },
  {
    "team": "広島東洋カープ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_c.html",
    "name": "モンテロ",
    "position": "一塁手",
    "games": 105,
    "pa": 396,
    "ab": 368,
    "runs": 23,
    "hits": 94,
    "doubles": 21,
    "triples": 1,
    "homeRuns": 9,
    "rbi": 41,
    "steals": 0,
    "walks": 23,
    "strikeouts": 89,
    "avg": 0.255,
    "slg": 0.391,
    "obp": 0.301,
    "positionDetail": "内野手",
    "fieldingSeed": 5
  },
  {
    "team": "広島東洋カープ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_c.html",
    "name": "菊池 涼介",
    "position": "二塁手",
    "games": 113,
    "pa": 389,
    "ab": 355,
    "runs": 30,
    "hits": 89,
    "doubles": 19,
    "triples": 0,
    "homeRuns": 4,
    "rbi": 28,
    "steals": 5,
    "walks": 14,
    "strikeouts": 70,
    "avg": 0.251,
    "slg": 0.338,
    "obp": 0.28,
    "positionDetail": "内野手",
    "fieldingSeed": 14
  },
  {
    "team": "広島東洋カープ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_c.html",
    "name": "中村 奨成",
    "position": "外野手",
    "games": 104,
    "pa": 368,
    "ab": 344,
    "runs": 43,
    "hits": 97,
    "doubles": 21,
    "triples": 3,
    "homeRuns": 9,
    "rbi": 33,
    "steals": 2,
    "walks": 17,
    "strikeouts": 48,
    "avg": 0.282,
    "slg": 0.439,
    "obp": 0.321,
    "positionDetail": "外野手",
    "fieldingSeed": 7
  },
  {
    "team": "広島東洋カープ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_c.html",
    "name": "矢野 雅哉",
    "position": "遊撃手",
    "games": 112,
    "pa": 335,
    "ab": 284,
    "runs": 24,
    "hits": 59,
    "doubles": 6,
    "triples": 1,
    "homeRuns": 1,
    "rbi": 19,
    "steals": 2,
    "walks": 27,
    "strikeouts": 69,
    "avg": 0.208,
    "slg": 0.246,
    "obp": 0.288,
    "positionDetail": "内野手",
    "fieldingSeed": 15
  },
  {
    "team": "広島東洋カープ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_c.html",
    "name": "佐々木 泰",
    "position": "三塁手",
    "games": 54,
    "pa": 187,
    "ab": 181,
    "runs": 11,
    "hits": 49,
    "doubles": 2,
    "triples": 1,
    "homeRuns": 0,
    "rbi": 6,
    "steals": 2,
    "walks": 5,
    "strikeouts": 23,
    "avg": 0.271,
    "slg": 0.293,
    "obp": 0.294,
    "positionDetail": "内野手",
    "fieldingSeed": 9
  },
  {
    "team": "東京ヤクルトスワローズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_s.html",
    "name": "オスナ",
    "position": "一塁手",
    "games": 141,
    "pa": 574,
    "ab": 528,
    "runs": 38,
    "hits": 135,
    "doubles": 22,
    "triples": 0,
    "homeRuns": 14,
    "rbi": 67,
    "steals": 4,
    "walks": 40,
    "strikeouts": 76,
    "avg": 0.256,
    "slg": 0.377,
    "obp": 0.307,
    "positionDetail": "内野手",
    "fieldingSeed": 4
  },
  {
    "team": "東京ヤクルトスワローズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_s.html",
    "name": "内山 壮真",
    "position": "外野手",
    "games": 116,
    "pa": 470,
    "ab": 423,
    "runs": 50,
    "hits": 111,
    "doubles": 26,
    "triples": 1,
    "homeRuns": 8,
    "rbi": 48,
    "steals": 8,
    "walks": 41,
    "strikeouts": 66,
    "avg": 0.262,
    "slg": 0.385,
    "obp": 0.326,
    "positionDetail": "外野手",
    "fieldingSeed": 8
  },
  {
    "team": "東京ヤクルトスワローズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_s.html",
    "name": "岩田 幸宏",
    "position": "外野手",
    "games": 126,
    "pa": 401,
    "ab": 357,
    "runs": 43,
    "hits": 95,
    "doubles": 8,
    "triples": 5,
    "homeRuns": 0,
    "rbi": 13,
    "steals": 14,
    "walks": 24,
    "strikeouts": 46,
    "avg": 0.266,
    "slg": 0.317,
    "obp": 0.322,
    "positionDetail": "外野手",
    "fieldingSeed": 9
  },
  {
    "team": "東京ヤクルトスワローズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_s.html",
    "name": "山田 哲人",
    "position": "二塁手",
    "games": 108,
    "pa": 377,
    "ab": 338,
    "runs": 25,
    "hits": 78,
    "doubles": 17,
    "triples": 0,
    "homeRuns": 12,
    "rbi": 37,
    "steals": 3,
    "walks": 33,
    "strikeouts": 63,
    "avg": 0.231,
    "slg": 0.388,
    "obp": 0.3,
    "positionDetail": "内野手",
    "fieldingSeed": 12
  },
  {
    "team": "東京ヤクルトスワローズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_s.html",
    "name": "古賀 優大",
    "position": "捕手",
    "games": 87,
    "pa": 291,
    "ab": 264,
    "runs": 16,
    "hits": 74,
    "doubles": 11,
    "triples": 0,
    "homeRuns": 2,
    "rbi": 16,
    "steals": 2,
    "walks": 12,
    "strikeouts": 23,
    "avg": 0.28,
    "slg": 0.345,
    "obp": 0.319,
    "fieldingSeed": 15
  },
  {
    "team": "東京ヤクルトスワローズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_s.html",
    "name": "赤羽 由紘",
    "position": "外野手",
    "games": 103,
    "pa": 290,
    "ab": 258,
    "runs": 22,
    "hits": 54,
    "doubles": 11,
    "triples": 1,
    "homeRuns": 2,
    "rbi": 19,
    "steals": 5,
    "walks": 18,
    "strikeouts": 66,
    "avg": 0.209,
    "slg": 0.283,
    "obp": 0.259,
    "positionDetail": "外野手",
    "fieldingSeed": 9
  },
  {
    "team": "東京ヤクルトスワローズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_s.html",
    "name": "長岡 秀樹",
    "position": "遊撃手",
    "games": 67,
    "pa": 261,
    "ab": 247,
    "runs": 20,
    "hits": 60,
    "doubles": 14,
    "triples": 2,
    "homeRuns": 0,
    "rbi": 13,
    "steals": 1,
    "walks": 8,
    "strikeouts": 21,
    "avg": 0.243,
    "slg": 0.316,
    "obp": 0.267,
    "positionDetail": "内野手",
    "fieldingSeed": 14
  },
  {
    "team": "東京ヤクルトスワローズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_s.html",
    "name": "サンタナ",
    "position": "外野手",
    "games": 60,
    "pa": 240,
    "ab": 212,
    "runs": 25,
    "hits": 58,
    "doubles": 11,
    "triples": 0,
    "homeRuns": 3,
    "rbi": 15,
    "steals": 1,
    "walks": 25,
    "strikeouts": 65,
    "avg": 0.274,
    "slg": 0.368,
    "obp": 0.358,
    "positionDetail": "外野手",
    "fieldingSeed": 8
  },
  {
    "team": "東京ヤクルトスワローズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_s.html",
    "name": "村上 宗隆",
    "position": "三塁手",
    "games": 56,
    "pa": 224,
    "ab": 187,
    "runs": 34,
    "hits": 51,
    "doubles": 7,
    "triples": 0,
    "homeRuns": 22,
    "rbi": 47,
    "steals": 4,
    "walks": 32,
    "strikeouts": 64,
    "avg": 0.273,
    "slg": 0.663,
    "obp": 0.379,
    "positionDetail": "内野手",
    "fieldingSeed": 9
  },
  {
    "team": "オリックス・バファローズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_b.html",
    "name": "頓宮 裕真",
    "position": "一塁手",
    "games": 129,
    "pa": 525,
    "ab": 473,
    "runs": 41,
    "hits": 118,
    "doubles": 20,
    "triples": 0,
    "homeRuns": 13,
    "rbi": 54,
    "steals": 1,
    "walks": 43,
    "strikeouts": 81,
    "avg": 0.249,
    "slg": 0.374,
    "obp": 0.316,
    "positionDetail": "内野手",
    "fieldingSeed": 4
  },
  {
    "team": "オリックス・バファローズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_b.html",
    "name": "太田 椋",
    "position": "二塁手",
    "games": 113,
    "pa": 496,
    "ab": 448,
    "runs": 42,
    "hits": 127,
    "doubles": 10,
    "triples": 0,
    "homeRuns": 10,
    "rbi": 52,
    "steals": 0,
    "walks": 33,
    "strikeouts": 102,
    "avg": 0.283,
    "slg": 0.373,
    "obp": 0.337,
    "positionDetail": "内野手",
    "fieldingSeed": 13
  },
  {
    "team": "オリックス・バファローズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_b.html",
    "name": "中川 圭太",
    "position": "外野手",
    "games": 119,
    "pa": 463,
    "ab": 433,
    "runs": 54,
    "hits": 123,
    "doubles": 26,
    "triples": 1,
    "homeRuns": 12,
    "rbi": 53,
    "steals": 10,
    "walks": 20,
    "strikeouts": 49,
    "avg": 0.284,
    "slg": 0.432,
    "obp": 0.314,
    "positionDetail": "外野手",
    "fieldingSeed": 9
  },
  {
    "team": "オリックス・バファローズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_b.html",
    "name": "杉本 裕太郎",
    "position": "外野手",
    "games": 119,
    "pa": 455,
    "ab": 401,
    "runs": 48,
    "hits": 104,
    "doubles": 15,
    "triples": 2,
    "homeRuns": 16,
    "rbi": 53,
    "steals": 1,
    "walks": 38,
    "strikeouts": 123,
    "avg": 0.259,
    "slg": 0.426,
    "obp": 0.332,
    "positionDetail": "外野手",
    "fieldingSeed": 7
  },
  {
    "team": "オリックス・バファローズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_b.html",
    "name": "廣岡 大志",
    "position": "外野手",
    "games": 118,
    "pa": 453,
    "ab": 402,
    "runs": 43,
    "hits": 102,
    "doubles": 15,
    "triples": 1,
    "homeRuns": 7,
    "rbi": 34,
    "steals": 9,
    "walks": 39,
    "strikeouts": 90,
    "avg": 0.254,
    "slg": 0.348,
    "obp": 0.317,
    "positionDetail": "外野手",
    "fieldingSeed": 8
  },
  {
    "team": "オリックス・バファローズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_b.html",
    "name": "紅林 弘太郎",
    "position": "遊撃手",
    "games": 116,
    "pa": 447,
    "ab": 400,
    "runs": 36,
    "hits": 104,
    "doubles": 20,
    "triples": 1,
    "homeRuns": 9,
    "rbi": 43,
    "steals": 1,
    "walks": 35,
    "strikeouts": 57,
    "avg": 0.26,
    "slg": 0.383,
    "obp": 0.321,
    "positionDetail": "内野手",
    "fieldingSeed": 16
  },
  {
    "team": "オリックス・バファローズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_b.html",
    "name": "西川 龍馬",
    "position": "外野手",
    "games": 96,
    "pa": 412,
    "ab": 387,
    "runs": 29,
    "hits": 120,
    "doubles": 23,
    "triples": 1,
    "homeRuns": 5,
    "rbi": 40,
    "steals": 4,
    "walks": 18,
    "strikeouts": 60,
    "avg": 0.31,
    "slg": 0.413,
    "obp": 0.343,
    "positionDetail": "外野手",
    "fieldingSeed": 7
  },
  {
    "team": "オリックス・バファローズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_b.html",
    "name": "若月 健矢",
    "position": "捕手",
    "games": 121,
    "pa": 400,
    "ab": 368,
    "runs": 30,
    "hits": 100,
    "doubles": 16,
    "triples": 2,
    "homeRuns": 6,
    "rbi": 31,
    "steals": 2,
    "walks": 16,
    "strikeouts": 61,
    "avg": 0.272,
    "slg": 0.375,
    "obp": 0.314,
    "fieldingSeed": 15
  },
  {
    "team": "オリックス・バファローズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_b.html",
    "name": "宗 佑磨",
    "position": "三塁手",
    "games": 98,
    "pa": 388,
    "ab": 349,
    "runs": 33,
    "hits": 82,
    "doubles": 12,
    "triples": 1,
    "homeRuns": 6,
    "rbi": 28,
    "steals": 3,
    "walks": 26,
    "strikeouts": 48,
    "avg": 0.235,
    "slg": 0.327,
    "obp": 0.304,
    "positionDetail": "内野手",
    "fieldingSeed": 9
  },
  {
    "team": "東北楽天ゴールデンイーグルス",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_e.html",
    "name": "村林 一輝",
    "position": "三塁手",
    "games": 137,
    "pa": 557,
    "ab": 513,
    "runs": 41,
    "hits": 144,
    "doubles": 14,
    "triples": 0,
    "homeRuns": 3,
    "rbi": 51,
    "steals": 6,
    "walks": 28,
    "strikeouts": 102,
    "avg": 0.281,
    "slg": 0.326,
    "obp": 0.32,
    "positionDetail": "内野手",
    "fieldingSeed": 7
  },
  {
    "team": "東北楽天ゴールデンイーグルス",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_e.html",
    "name": "中島 大輔",
    "position": "外野手",
    "games": 124,
    "pa": 491,
    "ab": 462,
    "runs": 51,
    "hits": 123,
    "doubles": 11,
    "triples": 5,
    "homeRuns": 6,
    "rbi": 31,
    "steals": 22,
    "walks": 17,
    "strikeouts": 75,
    "avg": 0.266,
    "slg": 0.351,
    "obp": 0.294,
    "positionDetail": "外野手",
    "fieldingSeed": 8
  },
  {
    "team": "東北楽天ゴールデンイーグルス",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_e.html",
    "name": "宗山 塁",
    "position": "遊撃手",
    "games": 122,
    "pa": 460,
    "ab": 430,
    "runs": 32,
    "hits": 112,
    "doubles": 19,
    "triples": 3,
    "homeRuns": 3,
    "rbi": 27,
    "steals": 7,
    "walks": 20,
    "strikeouts": 82,
    "avg": 0.26,
    "slg": 0.34,
    "obp": 0.289,
    "positionDetail": "内野手",
    "fieldingSeed": 16
  },
  {
    "team": "東北楽天ゴールデンイーグルス",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_e.html",
    "name": "辰己 涼介",
    "position": "外野手",
    "games": 114,
    "pa": 422,
    "ab": 367,
    "runs": 36,
    "hits": 88,
    "doubles": 12,
    "triples": 2,
    "homeRuns": 7,
    "rbi": 32,
    "steals": 20,
    "walks": 40,
    "strikeouts": 91,
    "avg": 0.24,
    "slg": 0.341,
    "obp": 0.325,
    "positionDetail": "外野手",
    "fieldingSeed": 7
  },
  {
    "team": "東北楽天ゴールデンイーグルス",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_e.html",
    "name": "浅村 栄斗",
    "position": "一塁手",
    "games": 96,
    "pa": 389,
    "ab": 331,
    "runs": 27,
    "hits": 79,
    "doubles": 13,
    "triples": 1,
    "homeRuns": 9,
    "rbi": 34,
    "steals": 1,
    "walks": 51,
    "strikeouts": 81,
    "avg": 0.239,
    "slg": 0.366,
    "obp": 0.35,
    "positionDetail": "内野手",
    "fieldingSeed": 5
  },
  {
    "team": "東北楽天ゴールデンイーグルス",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_e.html",
    "name": "小深田 大翔",
    "position": "二塁手",
    "games": 124,
    "pa": 357,
    "ab": 299,
    "runs": 36,
    "hits": 65,
    "doubles": 5,
    "triples": 2,
    "homeRuns": 1,
    "rbi": 14,
    "steals": 28,
    "walks": 40,
    "strikeouts": 65,
    "avg": 0.217,
    "slg": 0.258,
    "obp": 0.311,
    "positionDetail": "内野手",
    "fieldingSeed": 14
  },
  {
    "team": "東北楽天ゴールデンイーグルス",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_e.html",
    "name": "フランコ",
    "position": "三塁手",
    "games": 101,
    "pa": 347,
    "ab": 317,
    "runs": 21,
    "hits": 75,
    "doubles": 9,
    "triples": 0,
    "homeRuns": 7,
    "rbi": 32,
    "steals": 0,
    "walks": 24,
    "strikeouts": 65,
    "avg": 0.237,
    "slg": 0.331,
    "obp": 0.288,
    "positionDetail": "内野手",
    "fieldingSeed": 7
  },
  {
    "team": "東北楽天ゴールデンイーグルス",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_e.html",
    "name": "黒川 史陽",
    "position": "二塁手",
    "games": 83,
    "pa": 343,
    "ab": 301,
    "runs": 32,
    "hits": 90,
    "doubles": 8,
    "triples": 1,
    "homeRuns": 4,
    "rbi": 33,
    "steals": 1,
    "walks": 35,
    "strikeouts": 56,
    "avg": 0.299,
    "slg": 0.372,
    "obp": 0.372,
    "positionDetail": "内野手",
    "fieldingSeed": 13
  },
  {
    "team": "東北楽天ゴールデンイーグルス",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_e.html",
    "name": "ボイト",
    "position": "一塁手",
    "games": 67,
    "pa": 276,
    "ab": 243,
    "runs": 29,
    "hits": 73,
    "doubles": 9,
    "triples": 0,
    "homeRuns": 13,
    "rbi": 39,
    "steals": 0,
    "walks": 27,
    "strikeouts": 59,
    "avg": 0.3,
    "slg": 0.498,
    "obp": 0.384,
    "positionDetail": "内野手",
    "fieldingSeed": 6
  },
  {
    "team": "埼玉西武ライオンズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_l.html",
    "name": "ネビン",
    "position": "一塁手",
    "games": 137,
    "pa": 570,
    "ab": 509,
    "runs": 51,
    "hits": 141,
    "doubles": 24,
    "triples": 0,
    "homeRuns": 21,
    "rbi": 63,
    "steals": 2,
    "walks": 45,
    "strikeouts": 78,
    "avg": 0.277,
    "slg": 0.448,
    "obp": 0.346,
    "positionDetail": "内野手",
    "fieldingSeed": 4
  },
  {
    "team": "埼玉西武ライオンズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_l.html",
    "name": "西川 愛也",
    "position": "外野手",
    "games": 124,
    "pa": 553,
    "ab": 507,
    "runs": 64,
    "hits": 134,
    "doubles": 26,
    "triples": 3,
    "homeRuns": 10,
    "rbi": 38,
    "steals": 25,
    "walks": 32,
    "strikeouts": 80,
    "avg": 0.264,
    "slg": 0.387,
    "obp": 0.318,
    "positionDetail": "外野手",
    "fieldingSeed": 8
  },
  {
    "team": "埼玉西武ライオンズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_l.html",
    "name": "渡部 聖弥",
    "position": "外野手",
    "games": 109,
    "pa": 452,
    "ab": 425,
    "runs": 42,
    "hits": 110,
    "doubles": 16,
    "triples": 3,
    "homeRuns": 12,
    "rbi": 43,
    "steals": 2,
    "walks": 21,
    "strikeouts": 85,
    "avg": 0.259,
    "slg": 0.395,
    "obp": 0.299,
    "positionDetail": "外野手",
    "fieldingSeed": 9
  },
  {
    "team": "埼玉西武ライオンズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_l.html",
    "name": "長谷川 信哉",
    "position": "外野手",
    "games": 132,
    "pa": 450,
    "ab": 400,
    "runs": 42,
    "hits": 90,
    "doubles": 16,
    "triples": 3,
    "homeRuns": 6,
    "rbi": 36,
    "steals": 9,
    "walks": 33,
    "strikeouts": 56,
    "avg": 0.225,
    "slg": 0.325,
    "obp": 0.286,
    "positionDetail": "外野手",
    "fieldingSeed": 7
  },
  {
    "team": "埼玉西武ライオンズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_l.html",
    "name": "滝澤 夏央",
    "position": "二塁手",
    "games": 125,
    "pa": 438,
    "ab": 385,
    "runs": 31,
    "hits": 90,
    "doubles": 4,
    "triples": 0,
    "homeRuns": 0,
    "rbi": 14,
    "steals": 21,
    "walks": 28,
    "strikeouts": 67,
    "avg": 0.234,
    "slg": 0.244,
    "obp": 0.289,
    "positionDetail": "内野手",
    "fieldingSeed": 13
  },
  {
    "team": "埼玉西武ライオンズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_l.html",
    "name": "外崎 修汰",
    "position": "三塁手",
    "games": 115,
    "pa": 415,
    "ab": 359,
    "runs": 29,
    "hits": 84,
    "doubles": 13,
    "triples": 1,
    "homeRuns": 5,
    "rbi": 34,
    "steals": 6,
    "walks": 39,
    "strikeouts": 72,
    "avg": 0.234,
    "slg": 0.318,
    "obp": 0.31,
    "positionDetail": "内野手",
    "fieldingSeed": 9
  },
  {
    "team": "埼玉西武ライオンズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_l.html",
    "name": "源田 壮亮",
    "position": "遊撃手",
    "games": 104,
    "pa": 361,
    "ab": 320,
    "runs": 21,
    "hits": 67,
    "doubles": 11,
    "triples": 5,
    "homeRuns": 0,
    "rbi": 20,
    "steals": 8,
    "walks": 25,
    "strikeouts": 60,
    "avg": 0.209,
    "slg": 0.275,
    "obp": 0.269,
    "positionDetail": "内野手",
    "fieldingSeed": 14
  },
  {
    "team": "埼玉西武ライオンズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_l.html",
    "name": "古賀 悠斗",
    "position": "捕手",
    "games": 112,
    "pa": 328,
    "ab": 289,
    "runs": 26,
    "hits": 66,
    "doubles": 8,
    "triples": 0,
    "homeRuns": 7,
    "rbi": 21,
    "steals": 1,
    "walks": 32,
    "strikeouts": 62,
    "avg": 0.228,
    "slg": 0.329,
    "obp": 0.305,
    "fieldingSeed": 15
  },
  {
    "team": "埼玉西武ライオンズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_l.html",
    "name": "セデーニョ",
    "position": "一塁手",
    "games": 74,
    "pa": 243,
    "ab": 224,
    "runs": 13,
    "hits": 51,
    "doubles": 6,
    "triples": 1,
    "homeRuns": 7,
    "rbi": 26,
    "steals": 0,
    "walks": 15,
    "strikeouts": 50,
    "avg": 0.228,
    "slg": 0.357,
    "obp": 0.28,
    "positionDetail": "内野手",
    "fieldingSeed": 6
  },
  {
    "team": "千葉ロッテマリーンズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_m.html",
    "name": "藤原 恭大",
    "position": "外野手",
    "games": 107,
    "pa": 452,
    "ab": 409,
    "runs": 38,
    "hits": 111,
    "doubles": 12,
    "triples": 6,
    "homeRuns": 4,
    "rbi": 24,
    "steals": 15,
    "walks": 33,
    "strikeouts": 80,
    "avg": 0.271,
    "slg": 0.359,
    "obp": 0.335,
    "positionDetail": "外野手",
    "fieldingSeed": 7
  },
  {
    "team": "千葉ロッテマリーンズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_m.html",
    "name": "寺地 隆成",
    "position": "捕手",
    "games": 116,
    "pa": 445,
    "ab": 414,
    "runs": 33,
    "hits": 106,
    "doubles": 16,
    "triples": 0,
    "homeRuns": 5,
    "rbi": 33,
    "steals": 0,
    "walks": 19,
    "strikeouts": 67,
    "avg": 0.256,
    "slg": 0.331,
    "obp": 0.299,
    "fieldingSeed": 15
  },
  {
    "team": "千葉ロッテマリーンズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_m.html",
    "name": "西川 史礁",
    "position": "外野手",
    "games": 108,
    "pa": 444,
    "ab": 417,
    "runs": 42,
    "hits": 117,
    "doubles": 27,
    "triples": 3,
    "homeRuns": 3,
    "rbi": 37,
    "steals": 1,
    "walks": 16,
    "strikeouts": 85,
    "avg": 0.281,
    "slg": 0.381,
    "obp": 0.318,
    "positionDetail": "外野手",
    "fieldingSeed": 9
  },
  {
    "team": "千葉ロッテマリーンズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_m.html",
    "name": "山本 大斗",
    "position": "外野手",
    "games": 107,
    "pa": 417,
    "ab": 385,
    "runs": 40,
    "hits": 79,
    "doubles": 18,
    "triples": 0,
    "homeRuns": 11,
    "rbi": 33,
    "steals": 2,
    "walks": 24,
    "strikeouts": 112,
    "avg": 0.205,
    "slg": 0.338,
    "obp": 0.262,
    "positionDetail": "外野手",
    "fieldingSeed": 7
  },
  {
    "team": "千葉ロッテマリーンズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_m.html",
    "name": "髙部 瑛斗",
    "position": "外野手",
    "games": 111,
    "pa": 384,
    "ab": 357,
    "runs": 49,
    "hits": 102,
    "doubles": 15,
    "triples": 7,
    "homeRuns": 2,
    "rbi": 34,
    "steals": 20,
    "walks": 14,
    "strikeouts": 49,
    "avg": 0.286,
    "slg": 0.384,
    "obp": 0.314,
    "positionDetail": "外野手",
    "fieldingSeed": 8
  },
  {
    "team": "千葉ロッテマリーンズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_m.html",
    "name": "藤岡 裕大",
    "position": "二塁手",
    "games": 102,
    "pa": 373,
    "ab": 320,
    "runs": 25,
    "hits": 82,
    "doubles": 17,
    "triples": 1,
    "homeRuns": 4,
    "rbi": 25,
    "steals": 1,
    "walks": 42,
    "strikeouts": 67,
    "avg": 0.256,
    "slg": 0.353,
    "obp": 0.341,
    "positionDetail": "内野手",
    "fieldingSeed": 14
  },
  {
    "team": "千葉ロッテマリーンズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_m.html",
    "name": "ソト",
    "position": "一塁手",
    "games": 102,
    "pa": 367,
    "ab": 330,
    "runs": 31,
    "hits": 76,
    "doubles": 14,
    "triples": 0,
    "homeRuns": 13,
    "rbi": 44,
    "steals": 0,
    "walks": 32,
    "strikeouts": 98,
    "avg": 0.23,
    "slg": 0.391,
    "obp": 0.302,
    "positionDetail": "内野手",
    "fieldingSeed": 4
  },
  {
    "team": "千葉ロッテマリーンズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_m.html",
    "name": "安田 尚憲",
    "position": "三塁手",
    "games": 93,
    "pa": 350,
    "ab": 317,
    "runs": 22,
    "hits": 77,
    "doubles": 15,
    "triples": 0,
    "homeRuns": 0,
    "rbi": 25,
    "steals": 1,
    "walks": 25,
    "strikeouts": 65,
    "avg": 0.243,
    "slg": 0.29,
    "obp": 0.303,
    "positionDetail": "内野手",
    "fieldingSeed": 8
  },
  {
    "team": "千葉ロッテマリーンズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idb1_m.html",
    "name": "友杉 篤輝",
    "position": "遊撃手",
    "games": 116,
    "pa": 319,
    "ab": 278,
    "runs": 28,
    "hits": 64,
    "doubles": 11,
    "triples": 2,
    "homeRuns": 1,
    "rbi": 15,
    "steals": 7,
    "walks": 15,
    "strikeouts": 45,
    "avg": 0.23,
    "slg": 0.295,
    "obp": 0.275,
    "positionDetail": "内野手",
    "fieldingSeed": 16
  }
];

export const EXTRA_RAW_PITCHERS: NpbGeneratedPitcher[] = [
  {
    "team": "読売ジャイアンツ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idp1_g.html",
    "name": "山﨑 伊織",
    "games": 25,
    "wins": 11,
    "losses": 4,
    "battersFaced": 625,
    "innings": 156.1,
    "hitsAllowed": 124,
    "homeRunsAllowed": 9,
    "walks": 36,
    "strikeouts": 131,
    "runsAllowed": 40,
    "earnedRuns": 36,
    "eraValue": 2.07,
    "pitchingRole": "先発"
  },
  {
    "team": "読売ジャイアンツ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idp1_g.html",
    "name": "赤星 優志",
    "games": 22,
    "wins": 6,
    "losses": 9,
    "battersFaced": 488,
    "innings": 121,
    "hitsAllowed": 110,
    "homeRunsAllowed": 12,
    "walks": 19,
    "strikeouts": 88,
    "runsAllowed": 42,
    "earnedRuns": 36,
    "eraValue": 2.68,
    "pitchingRole": "先発"
  },
  {
    "team": "読売ジャイアンツ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idp1_g.html",
    "name": "戸郷 翔征",
    "games": 21,
    "wins": 8,
    "losses": 9,
    "battersFaced": 497,
    "innings": 111,
    "hitsAllowed": 124,
    "homeRunsAllowed": 8,
    "walks": 46,
    "strikeouts": 87,
    "runsAllowed": 58,
    "earnedRuns": 51,
    "eraValue": 4.14,
    "pitchingRole": "先発"
  },
  {
    "team": "読売ジャイアンツ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idp1_g.html",
    "name": "マルティネス",
    "games": 58,
    "wins": 3,
    "losses": 2,
    "battersFaced": 211,
    "innings": 56.2,
    "hitsAllowed": 32,
    "homeRunsAllowed": 3,
    "walks": 11,
    "strikeouts": 65,
    "runsAllowed": 7,
    "earnedRuns": 7,
    "eraValue": 1.11,
    "pitchingRole": "抑え"
  },
  {
    "team": "読売ジャイアンツ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idp1_g.html",
    "name": "大勢",
    "games": 62,
    "wins": 8,
    "losses": 4,
    "battersFaced": 244,
    "innings": 59.2,
    "hitsAllowed": 47,
    "homeRunsAllowed": 4,
    "walks": 14,
    "strikeouts": 60,
    "runsAllowed": 14,
    "earnedRuns": 14,
    "eraValue": 2.11,
    "pitchingRole": "中継ぎ"
  },
  {
    "team": "読売ジャイアンツ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idp1_g.html",
    "name": "中川 皓太",
    "games": 63,
    "wins": 2,
    "losses": 4,
    "battersFaced": 225,
    "innings": 52.1,
    "hitsAllowed": 55,
    "homeRunsAllowed": 4,
    "walks": 12,
    "strikeouts": 57,
    "runsAllowed": 16,
    "earnedRuns": 13,
    "eraValue": 2.24,
    "pitchingRole": "中継ぎ"
  },
  {
    "team": "中日ドラゴンズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idp1_d.html",
    "name": "髙橋 宏斗",
    "games": 26,
    "wins": 8,
    "losses": 10,
    "battersFaced": 690,
    "innings": 171.2,
    "hitsAllowed": 145,
    "homeRunsAllowed": 11,
    "walks": 50,
    "strikeouts": 138,
    "runsAllowed": 57,
    "earnedRuns": 54,
    "eraValue": 2.83,
    "pitchingRole": "先発"
  },
  {
    "team": "中日ドラゴンズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idp1_d.html",
    "name": "松葉 貴大",
    "games": 23,
    "wins": 7,
    "losses": 11,
    "battersFaced": 595,
    "innings": 145.2,
    "hitsAllowed": 136,
    "homeRunsAllowed": 9,
    "walks": 37,
    "strikeouts": 61,
    "runsAllowed": 45,
    "earnedRuns": 44,
    "eraValue": 2.72,
    "pitchingRole": "先発"
  },
  {
    "team": "中日ドラゴンズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idp1_d.html",
    "name": "大野 雄大",
    "games": 20,
    "wins": 11,
    "losses": 4,
    "battersFaced": 477,
    "innings": 120,
    "hitsAllowed": 95,
    "homeRunsAllowed": 6,
    "walks": 26,
    "strikeouts": 72,
    "runsAllowed": 34,
    "earnedRuns": 28,
    "eraValue": 2.1,
    "pitchingRole": "先発"
  },
  {
    "team": "中日ドラゴンズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idp1_d.html",
    "name": "松山 晋也",
    "games": 53,
    "wins": 0,
    "losses": 1,
    "battersFaced": 207,
    "innings": 52.2,
    "hitsAllowed": 40,
    "homeRunsAllowed": 2,
    "walks": 11,
    "strikeouts": 72,
    "runsAllowed": 9,
    "earnedRuns": 9,
    "eraValue": 1.54,
    "pitchingRole": "抑え"
  },
  {
    "team": "中日ドラゴンズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idp1_d.html",
    "name": "清水 達也",
    "games": 55,
    "wins": 4,
    "losses": 1,
    "battersFaced": 222,
    "innings": 52.1,
    "hitsAllowed": 49,
    "homeRunsAllowed": 0,
    "walks": 21,
    "strikeouts": 47,
    "runsAllowed": 15,
    "earnedRuns": 13,
    "eraValue": 2.24,
    "pitchingRole": "中継ぎ"
  },
  {
    "team": "中日ドラゴンズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idp1_d.html",
    "name": "藤嶋 健人",
    "games": 60,
    "wins": 1,
    "losses": 4,
    "battersFaced": 221,
    "innings": 52.2,
    "hitsAllowed": 48,
    "homeRunsAllowed": 3,
    "walks": 16,
    "strikeouts": 34,
    "runsAllowed": 21,
    "earnedRuns": 19,
    "eraValue": 3.25,
    "pitchingRole": "中継ぎ"
  },
  {
    "team": "広島東洋カープ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idp1_c.html",
    "name": "床田 寛樹",
    "games": 26,
    "wins": 9,
    "losses": 12,
    "battersFaced": 705,
    "innings": 171.1,
    "hitsAllowed": 158,
    "homeRunsAllowed": 13,
    "walks": 42,
    "strikeouts": 102,
    "runsAllowed": 64,
    "earnedRuns": 60,
    "eraValue": 3.15,
    "pitchingRole": "先発"
  },
  {
    "team": "広島東洋カープ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idp1_c.html",
    "name": "森下 暢仁",
    "games": 22,
    "wins": 6,
    "losses": 14,
    "battersFaced": 622,
    "innings": 152.1,
    "hitsAllowed": 140,
    "homeRunsAllowed": 6,
    "walks": 37,
    "strikeouts": 92,
    "runsAllowed": 53,
    "earnedRuns": 42,
    "eraValue": 2.48,
    "pitchingRole": "先発"
  },
  {
    "team": "広島東洋カープ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idp1_c.html",
    "name": "大瀬良 大地",
    "games": 23,
    "wins": 7,
    "losses": 9,
    "battersFaced": 571,
    "innings": 134.2,
    "hitsAllowed": 131,
    "homeRunsAllowed": 11,
    "walks": 38,
    "strikeouts": 88,
    "runsAllowed": 57,
    "earnedRuns": 52,
    "eraValue": 3.48,
    "pitchingRole": "先発"
  },
  {
    "team": "広島東洋カープ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idp1_c.html",
    "name": "森浦 大輔",
    "games": 60,
    "wins": 2,
    "losses": 3,
    "battersFaced": 224,
    "innings": 55.1,
    "hitsAllowed": 44,
    "homeRunsAllowed": 3,
    "walks": 15,
    "strikeouts": 60,
    "runsAllowed": 10,
    "earnedRuns": 10,
    "eraValue": 1.63,
    "pitchingRole": "抑え"
  },
  {
    "team": "広島東洋カープ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idp1_c.html",
    "name": "島内 颯太郎",
    "games": 60,
    "wins": 4,
    "losses": 2,
    "battersFaced": 224,
    "innings": 57.2,
    "hitsAllowed": 30,
    "homeRunsAllowed": 1,
    "walks": 21,
    "strikeouts": 57,
    "runsAllowed": 11,
    "earnedRuns": 9,
    "eraValue": 1.4,
    "pitchingRole": "中継ぎ"
  },
  {
    "team": "広島東洋カープ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idp1_c.html",
    "name": "栗林 良吏",
    "games": 55,
    "wins": 1,
    "losses": 1,
    "battersFaced": 210,
    "innings": 52.1,
    "hitsAllowed": 35,
    "homeRunsAllowed": 3,
    "walks": 18,
    "strikeouts": 54,
    "runsAllowed": 14,
    "earnedRuns": 13,
    "eraValue": 2.24,
    "pitchingRole": "中継ぎ"
  },
  {
    "team": "東京ヤクルトスワローズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idp1_s.html",
    "name": "吉村 貢司郎",
    "games": 22,
    "wins": 8,
    "losses": 6,
    "battersFaced": 546,
    "innings": 130,
    "hitsAllowed": 132,
    "homeRunsAllowed": 14,
    "walks": 27,
    "strikeouts": 85,
    "runsAllowed": 51,
    "earnedRuns": 44,
    "eraValue": 3.05,
    "pitchingRole": "先発"
  },
  {
    "team": "東京ヤクルトスワローズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idp1_s.html",
    "name": "ランバート",
    "games": 21,
    "wins": 3,
    "losses": 11,
    "battersFaced": 508,
    "innings": 116.1,
    "hitsAllowed": 123,
    "homeRunsAllowed": 11,
    "walks": 52,
    "strikeouts": 104,
    "runsAllowed": 57,
    "earnedRuns": 55,
    "eraValue": 4.26,
    "pitchingRole": "先発"
  },
  {
    "team": "東京ヤクルトスワローズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idp1_s.html",
    "name": "奥川 恭伸",
    "games": 18,
    "wins": 4,
    "losses": 8,
    "battersFaced": 457,
    "innings": 100,
    "hitsAllowed": 127,
    "homeRunsAllowed": 11,
    "walks": 33,
    "strikeouts": 77,
    "runsAllowed": 53,
    "earnedRuns": 48,
    "eraValue": 4.32,
    "pitchingRole": "先発"
  },
  {
    "team": "東京ヤクルトスワローズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idp1_s.html",
    "name": "星 知弥",
    "games": 44,
    "wins": 1,
    "losses": 2,
    "battersFaced": 177,
    "innings": 43,
    "hitsAllowed": 38,
    "homeRunsAllowed": 2,
    "walks": 13,
    "strikeouts": 41,
    "runsAllowed": 8,
    "earnedRuns": 8,
    "eraValue": 1.67,
    "pitchingRole": "抑え"
  },
  {
    "team": "東京ヤクルトスワローズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idp1_s.html",
    "name": "荘司 宏太",
    "games": 45,
    "wins": 2,
    "losses": 1,
    "battersFaced": 160,
    "innings": 42.2,
    "hitsAllowed": 19,
    "homeRunsAllowed": 1,
    "walks": 17,
    "strikeouts": 53,
    "runsAllowed": 5,
    "earnedRuns": 5,
    "eraValue": 1.05,
    "pitchingRole": "中継ぎ"
  },
  {
    "team": "東京ヤクルトスワローズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idp1_s.html",
    "name": "大西 広樹",
    "games": 50,
    "wins": 3,
    "losses": 3,
    "battersFaced": 193,
    "innings": 46,
    "hitsAllowed": 41,
    "homeRunsAllowed": 0,
    "walks": 14,
    "strikeouts": 35,
    "runsAllowed": 8,
    "earnedRuns": 6,
    "eraValue": 1.17,
    "pitchingRole": "中継ぎ"
  },
  {
    "team": "オリックス・バファローズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idp1_b.html",
    "name": "九里 亜蓮",
    "games": 25,
    "wins": 11,
    "losses": 8,
    "battersFaced": 678,
    "innings": 164.1,
    "hitsAllowed": 155,
    "homeRunsAllowed": 7,
    "walks": 48,
    "strikeouts": 114,
    "runsAllowed": 49,
    "earnedRuns": 44,
    "eraValue": 2.41,
    "pitchingRole": "先発"
  },
  {
    "team": "オリックス・バファローズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idp1_b.html",
    "name": "宮城 大弥",
    "games": 23,
    "wins": 7,
    "losses": 3,
    "battersFaced": 615,
    "innings": 150.1,
    "hitsAllowed": 135,
    "homeRunsAllowed": 6,
    "walks": 30,
    "strikeouts": 165,
    "runsAllowed": 41,
    "earnedRuns": 40,
    "eraValue": 2.39,
    "pitchingRole": "先発"
  },
  {
    "team": "オリックス・バファローズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idp1_b.html",
    "name": "エスピノーザ",
    "games": 23,
    "wins": 5,
    "losses": 8,
    "battersFaced": 566,
    "innings": 129.2,
    "hitsAllowed": 131,
    "homeRunsAllowed": 3,
    "walks": 47,
    "strikeouts": 119,
    "runsAllowed": 48,
    "earnedRuns": 43,
    "eraValue": 2.98,
    "pitchingRole": "先発"
  },
  {
    "team": "オリックス・バファローズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idp1_b.html",
    "name": "マチャド",
    "games": 58,
    "wins": 3,
    "losses": 6,
    "battersFaced": 233,
    "innings": 55.1,
    "hitsAllowed": 50,
    "homeRunsAllowed": 0,
    "walks": 16,
    "strikeouts": 68,
    "runsAllowed": 16,
    "earnedRuns": 14,
    "eraValue": 2.28,
    "pitchingRole": "抑え"
  },
  {
    "team": "オリックス・バファローズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idp1_b.html",
    "name": "ペルドモ",
    "games": 50,
    "wins": 2,
    "losses": 4,
    "battersFaced": 204,
    "innings": 48.1,
    "hitsAllowed": 50,
    "homeRunsAllowed": 1,
    "walks": 16,
    "strikeouts": 27,
    "runsAllowed": 18,
    "earnedRuns": 17,
    "eraValue": 3.17,
    "pitchingRole": "中継ぎ"
  },
  {
    "team": "オリックス・バファローズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idp1_b.html",
    "name": "岩嵜 翔",
    "games": 37,
    "wins": 4,
    "losses": 1,
    "battersFaced": 136,
    "innings": 34,
    "hitsAllowed": 26,
    "homeRunsAllowed": 0,
    "walks": 10,
    "strikeouts": 34,
    "runsAllowed": 8,
    "earnedRuns": 8,
    "eraValue": 2.12,
    "pitchingRole": "中継ぎ"
  },
  {
    "team": "東北楽天ゴールデンイーグルス",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idp1_e.html",
    "name": "藤井 聖",
    "games": 22,
    "wins": 6,
    "losses": 7,
    "battersFaced": 483,
    "innings": 109.2,
    "hitsAllowed": 121,
    "homeRunsAllowed": 9,
    "walks": 43,
    "strikeouts": 58,
    "runsAllowed": 46,
    "earnedRuns": 39,
    "eraValue": 3.2,
    "pitchingRole": "先発"
  },
  {
    "team": "東北楽天ゴールデンイーグルス",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idp1_e.html",
    "name": "岸 孝之",
    "games": 19,
    "wins": 6,
    "losses": 6,
    "battersFaced": 467,
    "innings": 109,
    "hitsAllowed": 125,
    "homeRunsAllowed": 10,
    "walks": 22,
    "strikeouts": 55,
    "runsAllowed": 54,
    "earnedRuns": 53,
    "eraValue": 4.38,
    "pitchingRole": "先発"
  },
  {
    "team": "東北楽天ゴールデンイーグルス",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idp1_e.html",
    "name": "古謝 樹",
    "games": 19,
    "wins": 7,
    "losses": 7,
    "battersFaced": 459,
    "innings": 107,
    "hitsAllowed": 118,
    "homeRunsAllowed": 8,
    "walks": 27,
    "strikeouts": 76,
    "runsAllowed": 48,
    "earnedRuns": 44,
    "eraValue": 3.7,
    "pitchingRole": "先発"
  },
  {
    "team": "東北楽天ゴールデンイーグルス",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idp1_e.html",
    "name": "則本 昂大",
    "games": 56,
    "wins": 3,
    "losses": 4,
    "battersFaced": 248,
    "innings": 56,
    "hitsAllowed": 60,
    "homeRunsAllowed": 4,
    "walks": 20,
    "strikeouts": 43,
    "runsAllowed": 19,
    "earnedRuns": 19,
    "eraValue": 3.05,
    "pitchingRole": "抑え"
  },
  {
    "team": "東北楽天ゴールデンイーグルス",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idp1_e.html",
    "name": "西口 直人",
    "games": 52,
    "wins": 3,
    "losses": 1,
    "battersFaced": 192,
    "innings": 50.2,
    "hitsAllowed": 29,
    "homeRunsAllowed": 3,
    "walks": 13,
    "strikeouts": 70,
    "runsAllowed": 6,
    "earnedRuns": 6,
    "eraValue": 1.07,
    "pitchingRole": "中継ぎ"
  },
  {
    "team": "東北楽天ゴールデンイーグルス",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idp1_e.html",
    "name": "藤平 尚真",
    "games": 62,
    "wins": 2,
    "losses": 2,
    "battersFaced": 238,
    "innings": 59.2,
    "hitsAllowed": 45,
    "homeRunsAllowed": 6,
    "walks": 20,
    "strikeouts": 66,
    "runsAllowed": 16,
    "earnedRuns": 14,
    "eraValue": 2.11,
    "pitchingRole": "中継ぎ"
  },
  {
    "team": "埼玉西武ライオンズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idp1_l.html",
    "name": "今井 達也",
    "games": 24,
    "wins": 10,
    "losses": 5,
    "battersFaced": 641,
    "innings": 163.2,
    "hitsAllowed": 101,
    "homeRunsAllowed": 6,
    "walks": 45,
    "strikeouts": 178,
    "runsAllowed": 38,
    "earnedRuns": 35,
    "eraValue": 1.92,
    "pitchingRole": "先発"
  },
  {
    "team": "埼玉西武ライオンズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idp1_l.html",
    "name": "隅田 知一郎",
    "games": 23,
    "wins": 10,
    "losses": 10,
    "battersFaced": 646,
    "innings": 159.2,
    "hitsAllowed": 142,
    "homeRunsAllowed": 12,
    "walks": 34,
    "strikeouts": 149,
    "runsAllowed": 47,
    "earnedRuns": 46,
    "eraValue": 2.59,
    "pitchingRole": "先発"
  },
  {
    "team": "埼玉西武ライオンズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idp1_l.html",
    "name": "髙橋 光成",
    "games": 24,
    "wins": 8,
    "losses": 9,
    "battersFaced": 616,
    "innings": 148,
    "hitsAllowed": 141,
    "homeRunsAllowed": 10,
    "walks": 41,
    "strikeouts": 88,
    "runsAllowed": 56,
    "earnedRuns": 50,
    "eraValue": 3.04,
    "pitchingRole": "先発"
  },
  {
    "team": "埼玉西武ライオンズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idp1_l.html",
    "name": "平良 海馬",
    "games": 54,
    "wins": 4,
    "losses": 2,
    "battersFaced": 220,
    "innings": 52.2,
    "hitsAllowed": 43,
    "homeRunsAllowed": 0,
    "walks": 21,
    "strikeouts": 53,
    "runsAllowed": 12,
    "earnedRuns": 10,
    "eraValue": 1.71,
    "pitchingRole": "抑え"
  },
  {
    "team": "埼玉西武ライオンズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idp1_l.html",
    "name": "甲斐野 央",
    "games": 47,
    "wins": 2,
    "losses": 3,
    "battersFaced": 180,
    "innings": 43.2,
    "hitsAllowed": 34,
    "homeRunsAllowed": 3,
    "walks": 18,
    "strikeouts": 36,
    "runsAllowed": 13,
    "earnedRuns": 12,
    "eraValue": 2.47,
    "pitchingRole": "中継ぎ"
  },
  {
    "team": "埼玉西武ライオンズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idp1_l.html",
    "name": "ウィンゲンター",
    "games": 49,
    "wins": 1,
    "losses": 4,
    "battersFaced": 188,
    "innings": 46.2,
    "hitsAllowed": 26,
    "homeRunsAllowed": 2,
    "walks": 20,
    "strikeouts": 69,
    "runsAllowed": 11,
    "earnedRuns": 9,
    "eraValue": 1.74,
    "pitchingRole": "中継ぎ"
  },
  {
    "team": "千葉ロッテマリーンズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idp1_m.html",
    "name": "種市 篤暉",
    "games": 24,
    "wins": 9,
    "losses": 8,
    "battersFaced": 666,
    "innings": 160.2,
    "hitsAllowed": 134,
    "homeRunsAllowed": 13,
    "walks": 50,
    "strikeouts": 161,
    "runsAllowed": 55,
    "earnedRuns": 47,
    "eraValue": 2.63,
    "pitchingRole": "先発"
  },
  {
    "team": "千葉ロッテマリーンズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idp1_m.html",
    "name": "小島 和哉",
    "games": 24,
    "wins": 8,
    "losses": 10,
    "battersFaced": 619,
    "innings": 145,
    "hitsAllowed": 144,
    "homeRunsAllowed": 20,
    "walks": 54,
    "strikeouts": 92,
    "runsAllowed": 67,
    "earnedRuns": 60,
    "eraValue": 3.72,
    "pitchingRole": "先発"
  },
  {
    "team": "千葉ロッテマリーンズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idp1_m.html",
    "name": "ボス",
    "games": 22,
    "wins": 3,
    "losses": 9,
    "battersFaced": 530,
    "innings": 125,
    "hitsAllowed": 129,
    "homeRunsAllowed": 8,
    "walks": 28,
    "strikeouts": 92,
    "runsAllowed": 57,
    "earnedRuns": 55,
    "eraValue": 3.96,
    "pitchingRole": "先発"
  },
  {
    "team": "千葉ロッテマリーンズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idp1_m.html",
    "name": "横山 陸人",
    "games": 50,
    "wins": 2,
    "losses": 4,
    "battersFaced": 227,
    "innings": 56.1,
    "hitsAllowed": 37,
    "homeRunsAllowed": 3,
    "walks": 16,
    "strikeouts": 47,
    "runsAllowed": 14,
    "earnedRuns": 13,
    "eraValue": 2.08,
    "pitchingRole": "抑え"
  },
  {
    "team": "千葉ロッテマリーンズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idp1_m.html",
    "name": "高野 脩汰",
    "games": 37,
    "wins": 5,
    "losses": 3,
    "battersFaced": 219,
    "innings": 53.2,
    "hitsAllowed": 43,
    "homeRunsAllowed": 3,
    "walks": 14,
    "strikeouts": 61,
    "runsAllowed": 11,
    "earnedRuns": 11,
    "eraValue": 1.84,
    "pitchingRole": "中継ぎ"
  },
  {
    "team": "千葉ロッテマリーンズ",
    "sourceUrl": "https://npb.jp/bis/2025/stats/idp1_m.html",
    "name": "鈴木 昭汰",
    "games": 29,
    "wins": 1,
    "losses": 3,
    "battersFaced": 122,
    "innings": 28,
    "hitsAllowed": 32,
    "homeRunsAllowed": 1,
    "walks": 8,
    "strikeouts": 27,
    "runsAllowed": 15,
    "earnedRuns": 15,
    "eraValue": 4.82,
    "pitchingRole": "中継ぎ"
  }
];
